### ISSUE TITLE
More bugs+Suggestions

### ISSUE THREAD

**Issue by EldyD** [ItsStev/scnr-issues#2]
1) No /vdestroy 
2) No gang color in name shown in the mainchat (ask me for help as to what i mean if u don't understand)
3) No gang bank
4) Sometimes, made accounts do not save (happened with virtualX, claims so)
5) No weed to be found on the server, commands exist
6) /aka doesn't work
7) /aod doesn't close after going afk (its fine tbh)
8) /setchatroom meaning mistake, if you use /setchatroom for e.g on a player named hydra, it will say "Hydra has set your chatroom", not "you have set hydra's chatroom"
9) /getwanted / /mostwanted do not exist
10) Timeouts are frequent, check why is that so xd

Suggestions:
1) Make drug systems, like weed gives you 50 hp back, meth gives u 100, coke gives u 150 hp, make it so that all drugs can be reaped and sold
2) Make a score system, X number of score gives you X number of coins/money
3) Make /gang color custom colors NON-VIP
4) Add a speedometer
5) Add a fuel system
6) Add more jobs such as banker n shit, i suggest to make the server more RP based becuz its already alot of DM and there are many RP players
7) Reduce the money requirement on cars n shit
8) Increase money robbed from stores (atleast 10-20k, easier to get money, 50-60k from banks)
9) Make the Militia bank again
10) Add a grey-ish color for other chatrooms for admins
11) Make it toggle-able to view the other chatroom messages for admins

**Comment by ItsStev** [comment]
Al bugs have been resolved, I will be considering your ideas
